export CUDA_VISIBLE_DEVICES=$1

lr=0.005
nitr=$2
wd=1e-5
I=96

python -u run.py --AutoCon --AutoCon_multiscales 96  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 2 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTh1.csv --model_id ICLR24_CRV --model AutoConCI --data ETTh1 --seq_len $I --label_len 48 --pred_len 96 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.01 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 192  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 1 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTh1.csv --model_id ICLR24_CRV --model AutoConCI --data ETTh1 --seq_len $I --label_len 48 --pred_len 192 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.01 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 336  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 1 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTh1.csv --model_id ICLR24_CRV --model AutoConCI --data ETTh1 --seq_len $I --label_len 48 --pred_len 336 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.01 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 720  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 1 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTh1.csv --model_id ICLR24_CRV --model AutoConCI --data ETTh1 --seq_len $I --label_len 48 --pred_len 720 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.01 --feature M

python -u run.py --AutoCon --AutoCon_multiscales 96  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 3 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTh2.csv --model_id ICLR24_CRV --model AutoConCI --data ETTh2 --seq_len $I --label_len 48 --pred_len 96 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 192  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 4 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTh2.csv --model_id ICLR24_CRV --model AutoConCI --data ETTh2 --seq_len $I --label_len 48 --pred_len 192 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 336  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 4 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTh2.csv --model_id ICLR24_CRV --model AutoConCI --data ETTh2 --seq_len $I --label_len 48 --pred_len 336 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 720  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 4 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTh2.csv --model_id ICLR24_CRV --model AutoConCI --data ETTh2 --seq_len $I --label_len 48 --pred_len 720 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature M

python -u run.py --AutoCon --AutoCon_multiscales 24 48  --AutoCon_wnorm ReVIN  --AutoCon_lambda 0.1 --d_model 4 --d_ff 4 --e_layers 8 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTm1.csv --model_id ICLR24_CRV --model AutoConCI --data ETTm1 --seq_len $I --label_len 48 --pred_len 96 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.005 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 24 48  --AutoCon_wnorm ReVIN  --AutoCon_lambda 0.01  --d_model 4 --d_ff 4 --e_layers 8 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTm1.csv --model_id ICLR24_CRV --model AutoConCI --data ETTm1 --seq_len $I --label_len 48 --pred_len 192 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.005 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 48  --AutoCon_wnorm ReVIN  --AutoCon_lambda 0.01  --d_model 4 --d_ff 4 --e_layers 6 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTm1.csv --model_id ICLR24_CRV --model AutoConCI --data ETTm1 --seq_len $I --label_len 48 --pred_len 336 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.005 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 24 48  --AutoCon_wnorm ReVIN  --AutoCon_lambda 0.1  --d_model 8 --d_ff 8 --e_layers 6 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTm1.csv --model_id ICLR24_CRV --model AutoConCI --data ETTm1 --seq_len $I --label_len 48 --pred_len 720 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.001 --feature M

python -u run.py --AutoCon --AutoCon_multiscales 96 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 4 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ICLR24_CRV --model AutoConCI --data ETTm2 --seq_len $I --label_len 48 --pred_len 96 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.005 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 192 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 2 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ICLR24_CRV --model AutoConCI --data ETTm2 --seq_len $I --label_len 48 --pred_len 192 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.005 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 336 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 2 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ICLR24_CRV --model AutoConCI --data ETTm2 --seq_len $I --label_len 48 --pred_len 336 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.005 --feature M
python -u run.py --AutoCon --AutoCon_multiscales 720 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0 --d_model 16 --d_ff 16 --e_layers 2 --target OT --c_out 7 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ICLR24_CRV --model AutoConCI --data ETTm2 --seq_len $I --label_len 48 --pred_len 720 --enc_in 7 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.005 --feature M