export CUDA_VISIBLE_DEVICES=$1

nitr=$2
wd=1e-5

python -u run.py --AutoCon  --AutoCon_multiscales 96  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 2 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTh1.csv --model_id ICLR24_CRV --model AutoConNet --data ETTh1 --seq_len 96 --label_len 48 --pred_len 96 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.01 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 720  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 2 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTh1.csv --model_id ICLR24_CRV --model AutoConNet --data ETTh1 --seq_len 96 --label_len 48 --pred_len 720 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 1440  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 32 --d_ff 32 --e_layers 1 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTh1.csv --model_id ICLR24_CRV --model AutoConNet --data ETTh1 --seq_len 96 --label_len 48 --pred_len 1440 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 1440  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 32 --d_ff 16 --e_layers 1 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTh1.csv --model_id ICLR24_CRV --model AutoConNet --data ETTh1 --seq_len 96 --label_len 48 --pred_len 2160 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature S

python -u run.py --AutoCon  --AutoCon_multiscales 96  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTh2.csv --model_id ICLR24_CRV --model AutoConNet --data ETTh2 --seq_len 96 --label_len 48 --pred_len 96 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 720  --AutoCon_wnorm LastVal  --AutoCon_lambda 0.1  --d_model 16 --d_ff 16 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTh2.csv --model_id ICLR24_CRV --model AutoConNet --data ETTh2 --seq_len 336 --label_len 48 --pred_len 720 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 720  --AutoCon_wnorm LastVal  --AutoCon_lambda 0.1  --d_model 16 --d_ff 16 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTh2.csv --model_id ICLR24_CRV --model AutoConNet --data ETTh2 --seq_len 168 --label_len 48 --pred_len 1440 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 720  --AutoCon_wnorm LastVal  --AutoCon_lambda 0.1  --d_model 8 --d_ff 8 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTh2.csv --model_id ICLR24_CRV --model AutoConNet --data ETTh2 --seq_len 168 --label_len 48 --pred_len 2160 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.001 --feature S

python -u run.py --AutoCon  --AutoCon_multiscales 192  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 32 --d_ff 32 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTm1.csv --model_id ICLR24_CRV --model AutoConNet --data ETTm1 --seq_len 192  --label_len 48 --pred_len 192 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 336  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 5 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTm1.csv --model_id ICLR24_CRV --model AutoConNet --data ETTm1 --seq_len 336  --label_len 48 --pred_len 1440 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.001 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 720  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 8 --d_ff 8 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTm1.csv --model_id ICLR24_CRV --model AutoConNet --data ETTm1 --seq_len 336  --label_len 48 --pred_len 2880 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.01 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 720  --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 8 --d_ff 8 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTm1.csv --model_id ICLR24_CRV --model AutoConNet --data ETTm1 --seq_len 336  --label_len 48 --pred_len 4320 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.005 --feature S

python -u run.py --AutoCon  --AutoCon_multiscales 192 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 4 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ICLR24_CRV --model AutoConNet --data ETTm2 --seq_len 192  --label_len 48 --pred_len 192 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 192 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 4 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ICLR24_CRV --model AutoConNet --data ETTm2 --seq_len 336  --label_len 48 --pred_len 1440 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.0001 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 720 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 4 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ICLR24_CRV --model AutoConNet --data ETTm2 --seq_len 336  --label_len 48 --pred_len 2880 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.0005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 720 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 4 --target OT --c_out 1 --root_path ./dataset/ETT-small --data_path ETTm2.csv --model_id ICLR24_CRV --model AutoConNet --data ETTm2 --seq_len 336  --label_len 48 --pred_len 4320 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.0005 --feature S

python -u run.py --AutoCon  --AutoCon_multiscales 96 --AutoCon_wnorm Mean  --AutoCon_lambda 0.001  --d_model 4 --d_ff 4 --e_layers 1 --target OT --c_out 1 --root_path ./dataset/electricity --data_path electricity.csv --model_id ICLR24_CRV --model AutoConNet --data electricity --seq_len 336 --label_len 48 --pred_len 96 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.001 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 336 --AutoCon_wnorm Mean  --AutoCon_lambda 0.001  --d_model 8 --d_ff 8 --e_layers 2 --target OT --c_out 1 --root_path ./dataset/electricity --data_path electricity.csv --model_id ICLR24_CRV --model AutoConNet --data electricity --seq_len 336 --label_len 48 --pred_len 720 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.001 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 336 --AutoCon_wnorm Mean  --AutoCon_lambda 0.001  --d_model 16 --d_ff 16 --e_layers 2 --target OT --c_out 1 --root_path ./dataset/electricity --data_path electricity.csv --model_id ICLR24_CRV --model AutoConNet --data electricity --seq_len 336 --label_len 48 --pred_len 1440 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.001 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 96 --AutoCon_wnorm Mean  --AutoCon_lambda 0.001  --d_model 16 --d_ff 16 --e_layers 2 --target OT --c_out 1 --root_path ./dataset/electricity --data_path electricity.csv --model_id ICLR24_CRV --model AutoConNet --data electricity --seq_len 168 --label_len 48 --pred_len 2160 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature S

python -u run.py --AutoCon  --AutoCon_multiscales 96 --AutoCon_wnorm ReVIN  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/traffic  --data_path traffic.csv --model_id ICLR24_CRV --model AutoConNet --data traffic --seq_len 336 --label_len 48 --pred_len 96 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 96 --AutoCon_wnorm ReVIN  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/traffic --data_path traffic.csv --model_id ICLR24_CRV --model AutoConNet --data traffic --seq_len 336 --label_len 48 --pred_len 720 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 96 --AutoCon_wnorm ReVIN  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/traffic --data_path traffic.csv --model_id ICLR24_CRV --model AutoConNet --data traffic --seq_len 336 --label_len 48 --pred_len 1440 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 96 --AutoCon_wnorm ReVIN  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/traffic --data_path traffic.csv --model_id ICLR24_CRV --model AutoConNet --data traffic --seq_len 336 --label_len 48 --pred_len 2160 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.005 --feature S

python -u run.py --AutoCon  --AutoCon_multiscales 336 --AutoCon_wnorm Mean  --AutoCon_lambda 0.001  --d_model 4 --d_ff 4 --e_layers 1 --target OT --c_out 1 --root_path ./dataset/weather --data_path weather.csv --model_id ICLR24_CRV --model AutoConNet --data weather --seq_len 336 --label_len 48 --pred_len 96 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.0003 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 720 --AutoCon_wnorm ReVIN  --AutoCon_lambda 1.0  --d_model 4 --d_ff 4 --e_layers 1 --target OT --c_out 1 --root_path ./dataset/weather --data_path weather.csv --model_id ICLR24_CRV --model AutoConNet --data weather --seq_len 336 --label_len 48 --pred_len 720 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.0001 --lradj fixed --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 336 --AutoCon_wnorm Decomp  --AutoCon_lambda 0.1  --d_model 8 --d_ff 8 --e_layers 2 --target OT --c_out 1 --root_path ./dataset/weather --data_path weather.csv --model_id ICLR24_CRV --model AutoConNet --data weather --seq_len 336 --label_len 48 --pred_len 1440 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.0001 --lradj fixed --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 720 --AutoCon_wnorm Decomp  --AutoCon_lambda 0.01  --d_model 8 --d_ff 8 --e_layers 2 --target OT --c_out 1 --root_path ./dataset/weather --data_path weather.csv --model_id ICLR24_CRV --model AutoConNet --data weather --seq_len 336 --label_len 48 --pred_len 2160 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 128 --learning_rate 0.0001 --lradj fixed --feature S

python -u run.py --AutoCon  --AutoCon_multiscales 48 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0   --d_model 16 --d_ff 16 --e_layers 1 --target OT --c_out 1 --root_path ./dataset/exchange_rate --data_path exchange_rate.csv --model_id ICLR24_CRV --model AutoConNet --data exchange_rate --seq_len 48 --label_len 24 --pred_len 48 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.001 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 48 360 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0   --d_model 8 --d_ff 16 --e_layers 1 --target OT --c_out 1 --root_path ./dataset/exchange_rate --data_path exchange_rate.csv --model_id ICLR24_CRV --model AutoConNet --data exchange_rate --seq_len 48 --label_len 24 --pred_len 360 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.0001 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 720 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0   --d_model 16 --d_ff 16 --e_layers 1 --target OT --c_out 1 --root_path ./dataset/exchange_rate --data_path exchange_rate.csv --model_id ICLR24_CRV --model AutoConNet --data exchange_rate --seq_len 48 --label_len 24 --pred_len 720 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.00001 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 48 540 1080 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0   --d_model 8 --d_ff 8 --e_layers 1 --target OT --c_out 1 --root_path ./dataset/exchange_rate --data_path exchange_rate.csv --model_id ICLR24_CRV --model AutoConNet --data exchange_rate --seq_len 48 --label_len 24 --pred_len 1080 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 64 --learning_rate 0.0001 --feature S

python -u run.py --AutoCon  --AutoCon_multiscales 14 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 4 --target OT --c_out 1 --root_path ./dataset/illness --data_path national_illness.csv --model_id ICLR24_CRV --model AutoConNet --data national_illness --seq_len 14 --label_len 7 --pred_len 14 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 12 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 28 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 16 --d_ff 16 --e_layers 4 --target OT --c_out 1 --root_path ./dataset/illness --data_path national_illness.csv --model_id ICLR24_CRV --model AutoConNet --data national_illness --seq_len 14 --label_len 7 --pred_len 28 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 12 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 56 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 128 --d_ff 128 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/illness --data_path national_illness.csv --model_id ICLR24_CRV --model AutoConNet --data national_illness --seq_len 14 --label_len 7 --pred_len 56 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 12 --learning_rate 0.005 --feature S
python -u run.py --AutoCon  --AutoCon_multiscales 112 --AutoCon_wnorm LastVal  --AutoCon_lambda 1.0  --d_model 128 --d_ff 128 --e_layers 3 --target OT --c_out 1 --root_path ./dataset/illness --data_path national_illness.csv --model_id ICLR24_CRV --model AutoConNet --data national_illness --seq_len 14 --label_len 7 --pred_len 112 --enc_in 1 --des 'Exp' --itr $nitr --batch_size 12 --learning_rate 0.005 --feature S